name: Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install spacy tensorflow pandas gitpython
        python -m spacy download en_core_web_sm

    - name: Run vulnerability prediction
      run: |
        python your_script.py

    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: vulnerability-results
        path: results/
