name: Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install checkov gitpython

    - name: Clone and scan Terraform code
      run: python clone_and_scan.py

    - name: Run Checkov to scan Terraform code
      run: |
        checkov -d terraform-infra --output-file-path $(pwd)/checkov_report.json --output json
      continue-on-error: true

    - name: List files after Checkov run
      run: ls -al $(pwd)
     
    - name: List files after Checkov run
      run: ls -al /home/runner/work/thesis/thesis


    - name: Generate remediation suggestions
      run: python remediation.py

    - name: Upload results and remediations
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: vulnerability-results
        path: checkov_report.json

    - name: Upload remediations
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: remediation-results
        path: remediations/
